# Generated by Django 5.1.6 on 2025-05-07 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosSocioeconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_desempeñada', models.CharField(max_length=255)),
                ('actividad_actual', models.CharField(max_length=255)),
                ('tipo_ingreso', models.CharField(max_length=255)),
                ('valor_mensual_promedio', models.FloatField()),
                ('clasificacion_ingreso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('TE', 'Tarjeta de Extranjeria'), ('CE', 'Cedula de Extranjeria'), ('NIT', 'Número de identificación Tributaria'), ('PP', 'Pasaporte'), ('PEP', 'Permiso Especial de Permanencia'), ('DIE', 'Documento de identificación extranjero'), ('NUIP', 'NUIP'), ('FOREIGN_NIT', 'NIT de otro pais')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('fk_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.departamentos')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='fk_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.paises'),
        ),
        migrations.CreateModel(
            name='TUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('tel_fijo', models.CharField(default='N/A', max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('genero', models.CharField(max_length=50)),
                ('matricula_profesional', models.CharField(default='N/A', max_length=255)),
                ('numero_documento', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo'), ('D', 'Divorciado'), ('UL', 'Union Libre')], max_length=11)),
                ('lugar_tipo_procedencia', models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1)),
                ('fk_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ciudades')),
                ('fk_datos_socioeconomicos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.datossocioeconomicos')),
                ('fk_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipodocumentos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
