# Generated by Django 5.1.6 on 2025-05-08 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espiritualidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertenece_grupo_religioso', models.BooleanField(default=True)),
                ('nombre_religion', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad_espiritual', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradosEscolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lee', models.BooleanField(default=True)),
                ('escribe', models.BooleanField(default=True)),
                ('tiene_primaria', models.BooleanField(default=True)),
                ('primaria_finalizada', models.BooleanField(default=True)),
                ('tiene_secundaria', models.BooleanField(default=True)),
                ('secundaria_finalizada', models.BooleanField(default=True)),
                ('tiene_tecnica', models.BooleanField(default=True)),
                ('nombre_tecnica', models.CharField(max_length=100)),
                ('tiene_tecnologia', models.BooleanField(default=True)),
                ('nombre_tecnologia', models.CharField(max_length=100)),
                ('tiene_pregrado', models.BooleanField(default=True)),
                ('nombre_pregrado', models.CharField(max_length=100)),
                ('tiene_posgrado', models.BooleanField(default=True)),
                ('nombre_posgrado', models.CharField(max_length=100)),
                ('otro_estudio', models.BooleanField(default=True)),
                ('nombre_otro_estudio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_activa', models.BooleanField(default=False)),
                ('nombre_actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad_fisica', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaGerontologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(auto_now=True)),
                ('actividad_desempeñada', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeguridadesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regimen', models.CharField(choices=[('C', 'Contributivo'), ('S', 'Subsidiado'), ('E', 'Especial'), ('N', 'Ninguno')], max_length=1)),
                ('nombre_eps', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_ips', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('tel_fijo', models.CharField(default='N/A', max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('genero', models.CharField(max_length=50)),
                ('matricula_profesional', models.CharField(default='N/A', max_length=255)),
                ('numero_documento', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo'), ('D', 'Divorciado'), ('UL', 'Union Libre')], max_length=11)),
                ('lugar_tipo_procedencia', models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1)),
                ('fk_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ciudades')),
                ('fk_datos_socioeconomicos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.datossocioeconomicos')),
                ('fk_espiritualidades', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.espiritualidades')),
                ('fk_habitos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.habitos')),
                ('fk_seguridades_sociales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.seguridadessociales')),
                ('fk_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tipodocumentos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TUsuario',
        ),
    ]
