# Generated by Django 3.2.25 on 2026-02-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_crear_grupo_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datossocioeconomico',
            old_name='actividad_desempeñada',
            new_name='actividad_desempenada',
        ),
        migrations.RenameField(
            model_name='datossocioeconomicosform',
            old_name='actividad_desempeñada',
            new_name='actividad_desempenada',
        ),
        migrations.AlterField(
            model_name='datossocioeconomicosform',
            name='actividad_desempenada',
            field=models.CharField(db_column='actividad_desempeñada', max_length=255),
        ),
        migrations.AlterField(
            model_name='evoluciondiariaenfermeria',
            name='identificacion_profesional',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='gradoescolaridad',
            name='tecnologo',
            field=models.CharField(blank=True, db_column='tecnologo', max_length=255),
        ),
    ]
